[package]
name = "line_width_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "naive"
path = "src/naive.rs"

[[bin]]
name = "voigt"
path = "src/voigt.rs"

[dependencies]
gnuplot = "0.0.39"
